 # source 'https://github.com/CocoaPods/Specs.git'
target 'DependencyInjectionDemos' do
 # platform :ios, '9.0' # or platform :osx, '10.10' if your target is OS X.
  use_frameworks!

  pod 'Swinject', '~> 2.0.0'
  pod 'SwinjectStoryboard', '~> 1.0.0'

end
